# Generated by Django 5.1.6 on 2025-07-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='couriex_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalcountry',
            name='couriex_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
