# Generated by Django 5.1.6 on 2025-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_country_couriex_code_historicalcountry_couriex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='can_call_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='can_verify_awb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='can_call_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalagency',
            name='can_verify_awb',
            field=models.BooleanField(default=False),
        ),
    ]
