# Generated by Django 5.1.6 on 2025-06-12 11:38

import base.mixins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("awb", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("price", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "awb",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="awb.awbdetail",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="Ledger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "ledger_type",
                    models.CharField(
                        choices=[("DEBIT", "DEBIT"), ("CREDIT", "CREDIT")],
                        editable=False,
                        max_length=10,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("LEDGER ENTRY", "LEDGER ENTRY"),
                            ("INVOICE", "INVOICE"),
                            ("PAYMENT", "PAYMENT"),
                            ("ADJUSTMENT", "ADJUSTMENT"),
                            ("OTHER", "OTHER"),
                        ],
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("particular", models.CharField(editable=False, max_length=255)),
                ("amount", models.FloatField(editable=False)),
                ("company_balance", models.FloatField(editable=False)),
                ("balance", models.FloatField(editable=False)),
                (
                    "reference_no",
                    models.CharField(
                        blank=True, editable=False, max_length=255, null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AWB", "AWB"),
                            ("INVOICE", "INVOICE"),
                            ("PAYMENT", "PAYMENT"),
                        ],
                        editable=False,
                        max_length=255,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, editable=False, null=True)),
                ("is_cancelled", models.BooleanField(default=False, editable=False)),
                (
                    "json_remarks",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.agency",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("amount", models.FloatField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Cash"), ("CHEQUE", "Cheque")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                (
                    "file_upload",
                    models.FileField(blank=True, null=True, upload_to="payments/"),
                ),
                ("is_cancelled", models.BooleanField(default=False)),
                ("json_remarks", models.JSONField(blank=True, null=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
    ]
