# Generated by Django 5.1.6 on 2025-07-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0006_awbapiresponse_created_at_awbapiresponse_is_deleted_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AddField(
            model_name='invoice',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CREDIT_CARD', 'Credit Card'), ('OTHER', 'Other')], help_text='The method of payment for this invoice', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='per_box_handling_fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='per_kg_customs_fee',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_paid_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='awb',
            field=models.ForeignKey(help_text='The AWB that this invoice is for', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='awb.awbdetail'),
        ),
    ]
