# Generated by Django 5.1.6 on 2025-07-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_invoice_price_invoice_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_box',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
