# Generated by Django 5.1.6 on 2025-06-10 17:46

import base.mixins
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AWBAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("api_response", models.TextField()),
                ("api_response_json", models.JSONField()),
                ("is_success", models.BooleanField(default=False)),
                ("response_code", models.CharField(max_length=255)),
                ("response_message", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="AWBAPIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=255)),
                ("response", models.JSONField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("request_url", models.TextField(blank=True, null=True)),
                ("label", models.TextField(blank=True, null=True)),
                ("pdf", models.TextField(blank=True, null=True)),
                ("is_success", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "AWB API Response",
                "verbose_name_plural": "AWB API Responses",
            },
        ),
        migrations.CreateModel(
            name="AWBDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_cash_user", models.BooleanField(default=False, null=True)),
                ("awbno", models.CharField(max_length=255, unique=True)),
                ("booking_datetime", models.DateTimeField(auto_now_add=True)),
                ("forwarding_number", models.TextField(blank=True, null=True)),
                ("forwarding_number_1", models.TextField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipment_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("content", models.TextField()),
                ("total_box", models.PositiveIntegerField(default=1)),
                ("is_in_run", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False, null=True)),
                ("is_invoice_generated", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("total_volumetric_weight", models.FloatField(default=0)),
                ("total_actual_weight", models.FloatField(default=0)),
                ("total_charged_weight", models.FloatField(default=0)),
                ("is_custom", models.BooleanField(default=False)),
                (
                    "barcode_image",
                    models.ImageField(blank=True, null=True, upload_to="barcodes/"),
                ),
                ("is_editable", models.BooleanField(default=True)),
                ("is_api_called_success", models.BooleanField(default=False)),
            ],
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="AWBStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LABEL CREATED", "LABEL CREATED"),
                            ("VERIFIED", "VERIFIED"),
                            (
                                "SHIPMENT HAS BEEN PICKED UP",
                                "SHIPMENT HAS BEEN PICKED UP",
                            ),
                            ("SHIPMENT PROCESSED", "SHIPMENT PROCESSED"),
                            ("ADDED TO RUN", "ADDED TO RUN"),
                            ("FORWARDING NO ASSIGNED", "FORWARDING NO ASSIGNED"),
                            ("SHIPMENT DEPARTURED", "SHIPMENT DEPARTURED"),
                            ("SHIPMENT IN TRANSIT", "SHIPMENT IN TRANSIT"),
                            ("SHIPMENT DELAYED", "SHIPMENT DELAYED"),
                            ("SHIPMENT ON HOLD", "SHIPMENT ON HOLD"),
                            ("SHIPMENT CUSTOM HELD", "SHIPMENT CUSTOM HELD"),
                            ("SHIPMENT OUT FOR DELIVERY", "SHIPMENT OUT FOR DELIVERY"),
                            ("SHIPMENT DELIVERED", "SHIPMENT DELIVERED"),
                            ("CANCELLED", "CANCELLED"),
                        ],
                        max_length=255,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="BoxDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("actual_weight", models.FloatField(help_text="Actual weight in Kg")),
                ("length", models.FloatField(help_text="Length in cm")),
                ("breadth", models.FloatField(help_text="Breadth in cm")),
                ("height", models.FloatField(help_text="Height in cm")),
                ("box_awb_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bag_no", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "charged_weight",
                    models.FloatField(
                        blank=True, help_text="Charged weight in Kg", null=True
                    ),
                ),
                (
                    "volumetric_weight",
                    models.FloatField(
                        blank=True, help_text="Volumetric weight in Kg", null=True
                    ),
                ),
                ("box_label", models.TextField(blank=True, null=True)),
                ("box_api_response", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Box Detail",
                "verbose_name_plural": "Box Details",
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="BoxItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=500)),
                ("hs_code", models.CharField(blank=True, max_length=500, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_weight", models.FloatField(blank=True, null=True)),
                ("unit_rate", models.FloatField(help_text="Rate per unit")),
                (
                    "amount",
                    models.FloatField(
                        editable=False, help_text="Calculated as Quantity * Unit Rate"
                    ),
                ),
            ],
            options={
                "verbose_name": "Box Item",
                "verbose_name_plural": "Box Items",
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="Consignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("person_name", models.CharField(max_length=255)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("post_zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "state_county",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "state_abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number 1"),
                ),
                (
                    "phone_number_2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number 2",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_front",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/fronts/"
                    ),
                ),
                (
                    "document_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/backs/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Consignee / Receiver (TO)",
                "verbose_name_plural": "Consignees / Receivers (TO)",
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="Consignor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("company", models.CharField(max_length=255)),
                ("person_name", models.CharField(max_length=255)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("post_zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "state_county",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_front",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/fronts/"
                    ),
                ),
                (
                    "document_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/backs/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipper / Consignor (FROM)",
                "verbose_name_plural": "Shippers / Consignors (FROM)",
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="HistoricalAWBDetail",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("is_cash_user", models.BooleanField(default=False, null=True)),
                ("awbno", models.CharField(db_index=True, max_length=255)),
                ("booking_datetime", models.DateTimeField(blank=True, editable=False)),
                ("forwarding_number", models.TextField(blank=True, null=True)),
                ("forwarding_number_1", models.TextField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "shipment_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("content", models.TextField()),
                ("total_box", models.PositiveIntegerField(default=1)),
                ("is_in_run", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_cancelled", models.BooleanField(default=False, null=True)),
                ("is_invoice_generated", models.BooleanField(default=False)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("total_volumetric_weight", models.FloatField(default=0)),
                ("total_actual_weight", models.FloatField(default=0)),
                ("total_charged_weight", models.FloatField(default=0)),
                ("is_custom", models.BooleanField(default=False)),
                (
                    "barcode_image",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("is_editable", models.BooleanField(default=True)),
                ("is_api_called_success", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical awb detail",
                "verbose_name_plural": "historical awb details",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBoxDetails",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("actual_weight", models.FloatField(help_text="Actual weight in Kg")),
                ("length", models.FloatField(help_text="Length in cm")),
                ("breadth", models.FloatField(help_text="Breadth in cm")),
                ("height", models.FloatField(help_text="Height in cm")),
                ("box_awb_no", models.CharField(blank=True, max_length=100, null=True)),
                ("bag_no", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "charged_weight",
                    models.FloatField(
                        blank=True, help_text="Charged weight in Kg", null=True
                    ),
                ),
                (
                    "volumetric_weight",
                    models.FloatField(
                        blank=True, help_text="Volumetric weight in Kg", null=True
                    ),
                ),
                ("box_label", models.TextField(blank=True, null=True)),
                ("box_api_response", models.TextField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Box Detail",
                "verbose_name_plural": "historical Box Details",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBoxItem",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=500)),
                ("hs_code", models.CharField(blank=True, max_length=500, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_weight", models.FloatField(blank=True, null=True)),
                ("unit_rate", models.FloatField(help_text="Rate per unit")),
                (
                    "amount",
                    models.FloatField(
                        editable=False, help_text="Calculated as Quantity * Unit Rate"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Box Item",
                "verbose_name_plural": "historical Box Items",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalConsignee",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("person_name", models.CharField(max_length=255)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("post_zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "state_county",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "state_abbreviation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Phone Number 1"),
                ),
                (
                    "phone_number_2",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Phone Number 2",
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_front",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_back",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Consignee / Receiver (TO)",
                "verbose_name_plural": "historical Consignees / Receivers (TO)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalConsignor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("company", models.CharField(max_length=255)),
                ("person_name", models.CharField(max_length=255)),
                ("address1", models.CharField(max_length=255)),
                ("address2", models.CharField(blank=True, max_length=255, null=True)),
                ("post_zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=100)),
                (
                    "state_county",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "document_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_front",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                (
                    "document_back",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Shipper / Consignor (FROM)",
                "verbose_name_plural": "historical Shippers / Consignors (FROM)",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumentType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical document type",
                "verbose_name_plural": "historical document types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHSCODE",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("description", models.CharField(db_index=True, max_length=255)),
                ("code", models.CharField(max_length=100)),
                ("search_key", models.CharField(blank=True, max_length=500, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical hscode",
                "verbose_name_plural": "historical hscodes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPickupRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("pickup_date", models.DateField()),
                (
                    "remarks",
                    models.TextField(
                        help_text="Any additional information about the pickup request"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "admin_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information about the pickup request by admin",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pickup request",
                "verbose_name_plural": "historical pickup requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProductType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical product type",
                "verbose_name_plural": "historical product types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalService",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical service",
                "verbose_name_plural": "historical services",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUnitType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Type of unit (e.g., kg, pcs, meter)",
                        max_length=50,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Unit Type",
                "verbose_name_plural": "historical Unit Types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HSCODE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("description", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=100)),
                ("search_key", models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="PickupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("pickup_date", models.DateField()),
                (
                    "remarks",
                    models.TextField(
                        help_text="Any additional information about the pickup request"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "admin_remarks",
                    models.TextField(
                        blank=True,
                        help_text="Any additional information about the pickup request by admin",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_default", models.BooleanField(default=False)),
            ],
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
        migrations.CreateModel(
            name="UnitType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Type of unit (e.g., kg, pcs, meter)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Unit Type",
                "verbose_name_plural": "Unit Types",
                "ordering": ["-priority"],
            },
            bases=(models.Model, base.mixins.CaseSensitiveFieldsMixin),
        ),
    ]
