# Generated by Django 5.1.6 on 2025-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbdetail',
            name='reason_for_export',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'COMMERCIAL'), ('GIFT', 'GIFT'), ('PERSONAL NOT FOR RESALE', 'PERSONAL NOT FOR RESALE'), ('SAMPLE', 'SAMPLE'), ('RETURN FOR REPAIR', 'RETURN FOR REPAIR'), ('RETURN AFTER REPAIR', 'RETURN AFTER REPAIR')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='reason_for_export',
            field=models.CharField(blank=True, choices=[('COMMERCIAL', 'COMMERCIAL'), ('GIFT', 'GIFT'), ('PERSONAL NOT FOR RESALE', 'PERSONAL NOT FOR RESALE'), ('SAMPLE', 'SAMPLE'), ('RETURN FOR REPAIR', 'RETURN FOR REPAIR'), ('RETURN AFTER REPAIR', 'RETURN AFTER REPAIR')], max_length=255, null=True),
        ),
    ]
