# Generated by Django 5.1.6 on 2025-07-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0003_awbdetail_reason_for_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbdetail',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('CIF', 'CIF'), ('CFR', 'CFR'), ('FOB', 'FOB')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='awbdetail',
            name='shipment_terms',
            field=models.CharField(blank=True, choices=[('DDU', 'DDU'), ('DUP', 'DUP')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='incoterms',
            field=models.CharField(blank=True, choices=[('CIF', 'CIF'), ('CFR', 'CFR'), ('FOB', 'FOB')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='shipment_terms',
            field=models.CharField(blank=True, choices=[('DDU', 'DDU'), ('DUP', 'DUP')], max_length=255, null=True),
        ),
    ]
