# Generated by Django 5.1.6 on 2025-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0004_awbdetail_incoterms_awbdetail_shipment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbdetail',
            name='label_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awbdetail',
            name='label_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awbdetail',
            name='label_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awbdetail',
            name='label_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='awbdetail',
            name='label_5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='label_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='label_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='label_3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='label_4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalawbdetail',
            name='label_5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
