# Generated by Django 5.1.6 on 2025-07-03 06:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0005_awbdetail_label_1_awbdetail_label_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbapiresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awbapiresponse',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awbapiresponse',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='awbapiresponse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
