# Generated by Django 5.1.6 on 2025-08-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0006_awbapiresponse_created_at_awbapiresponse_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awbdetail',
            name='shipment_terms',
            field=models.CharField(blank=True, choices=[('DDU', 'DDU'), ('DDP', 'DDP')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalawbdetail',
            name='shipment_terms',
            field=models.CharField(blank=True, choices=[('DDU', 'DDU'), ('DDP', 'DDP')], max_length=255, null=True),
        ),
    ]
