# Generated by Django 5.1.6 on 2025-09-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0007_alter_awbdetail_shipment_terms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='awbstatus',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='awbstatus',
            name='status',
            field=models.CharField(choices=[('LABEL CREATED', 'Label created'), ('SHIPMENT BOOKED', 'Shipment Booked'), ('SHIPMENT PICKED UP', 'Shipment Picked Up'), ('PROCESSED AT', 'Processed At'), ('DEPARTED FACILITY IN', 'Departed Facility In'), ('ON THE WAY', 'On the way'), ('ARRIVED AT SORT FACILITY', 'Arrived At Sort Facility'), ('ARRIVED AT DESTINATION', 'Arrived At Destination'), ('CUSTOMS STATUS UPDATED', 'Customs Status Updated'), ('CLEARANCE DELAY - IMPORT', 'Clearance delay - Import'), ('CLEARANCE IN PROGRESS', 'Clearance in progress'), ('CLEARANCE PROCESSING COMPLETE AT', 'Clearance Processing Complete At'), ('RECEIVED AT HUB', 'Received At Hub'), ('AT PARCEL DELIVERY CENTER', 'At parcel delivery center'), ('OUT FOR DELIVERY', 'Out for Delivery'), ('SHIPMENT ON HOLD', 'Shipment on Hold'), ('CANCELLED', 'Cancelled'), ('RETURNING PACKAGE TO SHIPPER', 'Returning package to shipper'), ('DELIVERED', 'Delivered')], max_length=255),
        ),
    ]
