# Generated by Django 5.1.6 on 2025-09-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awb', '0008_awbstatus_date_alter_awbstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awbstatus',
            name='date',
        ),
        migrations.AlterField(
            model_name='awbstatus',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
