# Generated by Django 5.1.6 on 2025-10-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='mobile',
            field=models.CharField(default=9800000000, max_length=255),
            preserve_default=False,
        ),
    ]
