# Generated by Django 5.1.6 on 2025-10-30 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_company_why_choose_us_card1_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='MyCompany',
        ),
    ]
