# Generated by Django 5.1.6 on 2025-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_prohibiteditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycompany',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
