# Generated by Django 5.1.6 on 2025-10-31 16:17

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_faq_answer_alter_faq_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycompany',
            name='address',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
    ]
